/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExecuteRouteImport } from './routes/execute'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppExecuteRouteImport } from './routes/app/execute'
import { Route as AppCreateRouteImport } from './routes/app/create'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects/$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects/$projectId/index'
import { Route as AppProjectsProjectIdTestsRouteImport } from './routes/app/projects/$projectId/tests'
import { Route as AppProjectsProjectIdContextRouteImport } from './routes/app/projects/$projectId/context'
import { Route as AppProjectsProjectIdTestsFeatureIdRouteImport } from './routes/app/projects/$projectId/tests/$featureId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecuteRoute = ExecuteRouteImport.update({
  id: '/execute',
  path: '/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExecuteRoute = AppExecuteRouteImport.update({
  id: '/execute',
  path: '/execute',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTestsRoute =
  AppProjectsProjectIdTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdContextRoute =
  AppProjectsProjectIdContextRouteImport.update({
    id: '/context',
    path: '/context',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTestsFeatureIdRoute =
  AppProjectsProjectIdTestsFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => AppProjectsProjectIdTestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/create': typeof CreateRoute
  '/execute': typeof ExecuteRoute
  '/login': typeof LoginRoute
  '/app/create': typeof AppCreateRoute
  '/app/execute': typeof AppExecuteRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/projects/$projectId/context': typeof AppProjectsProjectIdContextRoute
  '/app/projects/$projectId/tests': typeof AppProjectsProjectIdTestsRouteWithChildren
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/tests/$featureId': typeof AppProjectsProjectIdTestsFeatureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/execute': typeof ExecuteRoute
  '/login': typeof LoginRoute
  '/app/create': typeof AppCreateRoute
  '/app/execute': typeof AppExecuteRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$projectId/context': typeof AppProjectsProjectIdContextRoute
  '/app/projects/$projectId/tests': typeof AppProjectsProjectIdTestsRouteWithChildren
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/tests/$featureId': typeof AppProjectsProjectIdTestsFeatureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/create': typeof CreateRoute
  '/execute': typeof ExecuteRoute
  '/login': typeof LoginRoute
  '/app/create': typeof AppCreateRoute
  '/app/execute': typeof AppExecuteRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/projects/$projectId/context': typeof AppProjectsProjectIdContextRoute
  '/app/projects/$projectId/tests': typeof AppProjectsProjectIdTestsRouteWithChildren
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/tests/$featureId': typeof AppProjectsProjectIdTestsFeatureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/create'
    | '/execute'
    | '/login'
    | '/app/create'
    | '/app/execute'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/context'
    | '/app/projects/$projectId/tests'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/tests/$featureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/execute'
    | '/login'
    | '/app/create'
    | '/app/execute'
    | '/app'
    | '/app/projects/$projectId/context'
    | '/app/projects/$projectId/tests'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/tests/$featureId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/create'
    | '/execute'
    | '/login'
    | '/app/create'
    | '/app/execute'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/context'
    | '/app/projects/$projectId/tests'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/tests/$featureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CreateRoute: typeof CreateRoute
  ExecuteRoute: typeof ExecuteRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execute': {
      id: '/execute'
      path: '/execute'
      fullPath: '/execute'
      preLoaderRoute: typeof ExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/execute': {
      id: '/app/execute'
      path: '/execute'
      fullPath: '/app/execute'
      preLoaderRoute: typeof AppExecuteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/tests': {
      id: '/app/projects/$projectId/tests'
      path: '/tests'
      fullPath: '/app/projects/$projectId/tests'
      preLoaderRoute: typeof AppProjectsProjectIdTestsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/context': {
      id: '/app/projects/$projectId/context'
      path: '/context'
      fullPath: '/app/projects/$projectId/context'
      preLoaderRoute: typeof AppProjectsProjectIdContextRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/tests/$featureId': {
      id: '/app/projects/$projectId/tests/$featureId'
      path: '/$featureId'
      fullPath: '/app/projects/$projectId/tests/$featureId'
      preLoaderRoute: typeof AppProjectsProjectIdTestsFeatureIdRouteImport
      parentRoute: typeof AppProjectsProjectIdTestsRoute
    }
  }
}

interface AppProjectsProjectIdTestsRouteChildren {
  AppProjectsProjectIdTestsFeatureIdRoute: typeof AppProjectsProjectIdTestsFeatureIdRoute
}

const AppProjectsProjectIdTestsRouteChildren: AppProjectsProjectIdTestsRouteChildren =
  {
    AppProjectsProjectIdTestsFeatureIdRoute:
      AppProjectsProjectIdTestsFeatureIdRoute,
  }

const AppProjectsProjectIdTestsRouteWithChildren =
  AppProjectsProjectIdTestsRoute._addFileChildren(
    AppProjectsProjectIdTestsRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdContextRoute: typeof AppProjectsProjectIdContextRoute
  AppProjectsProjectIdTestsRoute: typeof AppProjectsProjectIdTestsRouteWithChildren
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdContextRoute: AppProjectsProjectIdContextRoute,
  AppProjectsProjectIdTestsRoute: AppProjectsProjectIdTestsRouteWithChildren,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppExecuteRoute: typeof AppExecuteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppExecuteRoute: AppExecuteRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CreateRoute: CreateRoute,
  ExecuteRoute: ExecuteRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
